# Generated by Django 4.2.5 on 2023-09-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Studyknight', '0002_free'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_txt', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('pub_date', models.DateTimeField(verbose_name='Date Published')),
                ('age', models.IntegerField()),
            ],
        ),
    ]
