# Generated by Django 4.2.5 on 2023-11-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Studyknight', '0004_context_remove_gd_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Omen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
    ]
